# Generated by Django 4.0.4 on 2022-05-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cabeca', models.CharField(max_length=20)),
                ('braco', models.CharField(max_length=20)),
                ('corpo', models.CharField(max_length=20)),
                ('capitador1', models.CharField(max_length=20)),
                ('capitador2', models.CharField(max_length=20)),
                ('imagem', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('criacao', models.DateTimeField(verbose_name='data de criação')),
            ],
        ),
    ]
